image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package

build_jar:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew bootRepackage
    - ./gradlew copyJarToRootDir
  artifacts:
    paths:
      - ./*.jar
  only:
    - master

package_to_docker_image:
  stage: package
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_REGISTRY_USER/jiusan-star:$CI_COMMIT_REF_SLUG" .
    - docker push "$DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/jiusan-star:$CI_COMMIT_REF_SLUG"
  only:
    - master
