image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

build_jar:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew bootRepackage
    - ./gradlew copyJarToRootDir
  artifacts:
    paths:
      - ./*.jar
  only:
    - master

package_to_docker_image:
  stage: package
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master

deploy_to_aliyun:
  stage: deploy
  before_script:
    - apk update && apk add sshpass
  script:
    - sshpass -V
    - export SSHPASS=$REMOTE_SERVER_PASSWD
    - echo $SSHPASS
    - sshpass -e StrictHostKeyChecking=no ssh root@www.marcux.space "docker pull registry.gitlab.com/linfaimom/jiusanstar"
