image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package

build-jar:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew bootRepackage
  only:
    - master

package-as-docker-image:
  image: gradle:latest
  stage: package
  script:
    - ./gradlew copyJarToRootDir
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master
