image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - package

unit_test:
 image: gradle:latest
 stage: test
 script:
   - ./gradlew test

build_jar:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew bootRepackage
    - ./gradlew copyJarToRootDir
  artifacts:
    paths:
      - ./*.jar
  only:
    - master

package_to_docker_image:
  stage: package
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_REGISTRY_IMAGE:latest" .
    - docker push "$DOCKER_REGISTRY_IMAGE:latest"
  only:
    - master
