image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

before_script:
  - apk update && apk add sshpass

build_jar:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew bootRepackage
    - ./gradlew copyJarToRootDir
  artifacts:
    paths:
      - ./*.jar
  only:
    - master

package_to_docker_image:
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master

deploy_on_aliyun:
  stage: deploy
  script:
    - sshpass -V
    - export SSHPASS="$REMOTE_SERVER_PASSWD"
    - sshpass -e scp -o stricthostkeychecking=no root@www.marcux.space
    - ls -al
    - docker pull registry.gitlab.com/linfaimom/jiusanstar
