image: docker:latest

stages:
  - test
  - build
  - package
  - deploy

unit_test:
 image: gradle:latest
 stage: test
 script:
   - ./gradlew test

build_jar:
  image: gradle:latest
  stage: build
  script:
    - ./gradlew bootRepackage
    - ./gradlew copyJarToRootDir
# 产出 jar，供 package 阶段生成 docker image 使用
  artifacts:
    paths:
      - ./*.jar
  only:
    - master

package_to_docker_image:
  stage: package
  before_script:
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker build --pull -t "$DOCKER_REGISTRY_IMAGE:latest" .
    - docker push "$DOCKER_REGISTRY_IMAGE:latest"
  only:
    - master

deploy_on_server:
  stage: deploy
# 不去 gitlab clone repository，毕竟 GFW 太强大
  variables:
    GIT_STRATEGY: none
# 不去下 build_jar 时候产生的 jar，毕竟 GFW 太强大
  dependencies: []
  script:
    - whoami
    - docker container ls
    - docker pull $DOCKER_CN_REGISTRY_IMAGE:latest
    - docker container rm -f jiusan-star
  after_script:
    - docker run --name="jiusan-star" -e "SPRING_PROFILES_ACTIVE=prod" -p 80:80 -p 443:443 --net="host" -d $DOCKER_CN_REGISTRY_IMAGE
  only:
    - master
  tags:
    - run-on-tencent
